# Generated by Django 2.0.6 on 2019-03-01 16:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('school', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=20)),
                ('hours', models.DecimalField(decimal_places=2, max_digits=999)),
                ('date_of_work', models.DateField(default='')),
                ('date_of_entry', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
